---
fedora_releasever: 42
base_box_url: https://dl.fedoraproject.org/pub/fedora/linux/releases/test/42_Beta/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-libvirt-42_Beta-1.4.x86_64.vagrant.libvirt.box
