- name: schedule PRCI autocleaner
  cron:
    name: "PRCI autocleaner"
    minute: "0"
    hour: "15"
    weekday: "7"
    job: python3 /root/freeipa-pr-ci/autocleaner.py --jobs_dir_exp 3
    user: root
    state: present
