---
- name: create config directory if it dosn't exist
  file:
    path: /root/.config/freeipa-pr-ci
    state: directory
    owner: root
    group: root
    mode: 0700

- name: copy prci.py configuration file
  template:
    src: config.yml
    dest: /root/.config/freeipa-pr-ci/config.yml
