---
- name: check if nested virtualization is enabled
  block:
    - command: cat /sys/module/kvm_intel/parameters/nested
      register: nested_virt_enabled
      changed_when: false
  rescue:
    - command: cat /sys/module/kvm_amd/parameters/nested
      register: nested_virt_enabled
      changed_when: false

- name: enable nested virtualization in kvm config
  blockinfile:
    dest: /etc/modprobe.d/kvm-intel.conf
    create: yes
    block: |
      options kvm-intel nested=1
  notify: reboot
  when: nested_virt_enabled.stdout == "N"
