#!/bin/bash

# Execute build and run test on PR given as argument

# Execute from the topology directory
cd "$(dirname "$0")"

./build $1
if [ $? -ne 0 ]; then
    exit $?
fi

# TODO Replace this with downloading packages from URL
rm -rf topology/rpms
cp -r topology/build/rpms topology/

./run-tests test_integration/test_simple_replication.py
exit $?

