#!/bin/python

import sys
import re
from tasks.task import PopenTask
from tasks.remote_storage import FedoraPeopleDownload, UUID_RE


build = sys.argv[1]
if not re.match(UUID_RE, build):
    raise Exception("provide job UUID")

FedoraPeopleDownload(build)()
