---
- name: testgroup
  win_domain_group:
    name: testgroup
    scope: global
    attributes:
      gidNumber: 10047

- name: group@group
  win_domain_group:
    name: group@group
    scope: global
    attributes:
      gidNumber: 10048

- name: testgroup1
  win_domain_group:
    name: testgroup1
    scope: global

- name: A test user with posix attributes defined
  include_role:
    name: windows/ipa-ad-data
    tasks_from: user.yml
  vars:
    options:
      Name: testuser
      GivenName: Test
      Surname: User
      AccountPassword: Secret123
      PasswordNeverExpires: $true
      Enabled: $true
      OtherAttributes: "@{'uidNumber'='10042'; 'gidNumber'='10047'; 'loginShell'='/bin/sh'; 'homeDirectory'='/home/testuser'; 'unixHomeDirectory'='/home/testuser'; 'gecos'='Test User'}"

- name: A test user with only posix attributes uidNumber defined
  include_role:
    name: windows/ipa-ad-data
    tasks_from: user.yml
  vars:
    options:
      Name: testuser1
      GivenName: Test1
      Surname: User1
      AccountPassword: Secret123
      PasswordNeverExpires: $true
      Enabled: $true
      OtherAttributes: "@{'uidNumber'='10050'; 'loginShell'='/bin/sh'; 'homeDirectory'='/home/testuser1'; 'unixHomeDirectory'='/home/testuser1'; 'gecos'='Test User1'}"

- name: A test user with gid but no corresponding group
  include_role:
    name: windows/ipa-ad-data
    tasks_from: user.yml
  vars:
    options:
      Name: testuser2
      GivenName: Test2
      Surname: User2
      AccountPassword: Secret123
      PasswordNeverExpires: $true
      Enabled: $true
      OtherAttributes: "@{'uidNumber'='10060'; 'gidNumber'='10049'; 'loginShell'='/bin/sh'; 'homeDirectory'='/home/testuser2'; 'unixHomeDirectory'='/home/testuser2'; 'gecos'='Test User2'}"

- name: set Test User primary group
  include_role:
    name: windows/ipa-ad-data
    tasks_from: primary_group.yml
  vars:
    user: testuser
    group: testgroup

- name: A test user without posix attributes defined
  include_role:
    name: windows/ipa-ad-data
    tasks_from: user.yml
  vars:
    options:
      Name: nonposixuser
      GivenName: Nonposix
      Surname: User
      AccountPassword: Secret123
      PasswordNeverExpires: $true
      Enabled: $true

- name: A test user without posix attributes defined and nondefault primarygroup
  include_role:
    name: windows/ipa-ad-data
    tasks_from: user.yml
  vars:
    options:
      Name: nonposixuser1
      GivenName: Nonposix1
      Surname: User1
      AccountPassword: Secret123
      PasswordNeverExpires: $true
      Enabled: $true
      user: nonposixuser1

- name: set Test User primary group
  include_role:
    name: windows/ipa-ad-data
    tasks_from: primary_group.yml
  vars:
    user: nonposixuser1
    group: testgroup1

- name: A test user with posix attributes which is disabled
  include_role:
    name: windows/ipa-ad-data
    tasks_from: user.yml
  vars:
    options:
      Name: disabledaduser
      GivenName: Disabledad
      Surname: User
      AccountPassword: Secret123
      PasswordNeverExpires: $true
      Enabled: $false
      OtherAttributes: "@{'uidNumber'='10043'; 'gidNumber'='10047'; 'loginShell'='/bin/sh'; 'homeDirectory'='/home/disableduser'}"

- name: create UPN suffix
  win_shell: Get-ADForest | Set-ADForest -UPNSuffixes @{add="UPNsuffix.com"}

- name: A user with UPN suffix
  include_role:
    name: windows/ipa-ad-data
    tasks_from: user.yml
  vars:
    options:
      Name: upnuser
      GivenName: UPN
      Surname: User
      AccountPassword: Secret123456
      PasswordNeverExpires: $true
      Enabled: $true
      UserPrincipalName: upnuser@UPNsuffix.com
      OtherAttributes: "@{'uidNumber'='10048'; 'gidNumber'='10047'; 'loginShell'='/bin/sh'; 'homeDirectory'='/home/upnuser'; 'gecos'='UPN User'}"

- name: set UPN User primary group
  include_role:
    name: windows/ipa-ad-data
    tasks_from: primary_group.yml
  vars:
    user: upnuser
    group: testgroup
