---
basedir: /root/openclose_pr

nightly_jobs:
  - name: testing_master
    weekdays: "1,3,5"
    hour: "23"
    minute: "00"
    flow: "ci"
    branch: "master"
    prci_config: "nightly_master.yaml"
  - name: testing_f29
    weekdays: "2,4"
    hour: "23"
    minute: "00"
    flow: "ci"
    branch: "master"
    prci_config: "nightly_f29.yaml"
  - name: testing_rawhide
    weekdays: "6"
    hour: "10"
    minute: "00"
    flow: "ci"
    branch: "master"
    prci_config: "nightly_rawhide.yaml"
  - name: testing_ipa-4.7
    weekdays: "7"
    hour: "10"
    minute: "00"
    flow: "ci"
    branch: "ipa-4-7"
    prci_config: "nightly_master.yaml"
  - name: testing_ipa-4.8
    weekdays: "6"
    hour: "15"
    minute: "00"
    flow: "ci"
    branch: "ipa-4-8"
    prci_config: "nightly_master.yaml"
  - name: testing_ipa-4.6
    weekdays: "7"
    hour: "15"
    minute: "00"
    flow: "ci"
    branch: "ipa-4-6"
    prci_config: "nightly_ipa-4-6.yaml"
  - name: testing_pki
    weekdays: "7"
    hour: "20"
    minute: "00"
    flow: "pki"
    branch: "master"
    prci_config: "nightly_master_pki.yaml"
