---
- name: install Python 3 deps for ansible modules
  dnf:
    name: python3-libselinux
    state: latest

- name: set selinux mode
  selinux:
    state: "{{ selinux_mode }}"
    policy: targeted

- name: disable distro repositories
  shell: "dnf config-manager setopt {{ item }}.enabled=0"
  with_items:
    - fedora
    - updates
    - updates-testing
    - fedora-cisco-openh264

- name: enable selected repositories
  shell: "dnf config-manager setopt {{ item.key }}.enabled=1"
  with_dict:
    fedora: "{{ repo_fedora_enabled }}"
    updates: "{{ repo_updates_enabled }}"
  when: fedora_version != 'rawhide' and item.value

- name: configure rawhide repository
  shell: "dnf config-manager setopt rawhide.enabled={{ '1' if repo_rawhide_enabled else '0' }}"
  when: fedora_version == 'rawhide'

- name: configure FreeIPA COPR repo
  shell: "dnf copr enable -y @freeipa/freeipa-{{ freeipa_version }}"
  when: repo_freeipa_copr_enabled
