---
# tasks file for win-ad-common

- wait_for_connection:

- name: Install AD Domain Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes

- name: Turn off firewall
  win_shell: |
    Get-NetFirewallProfile | Set-NetFirewallProfile -Enabled False
