---
- name: "set default mock config"
  file:
    src: "/etc/mock/{{ build_chroot }}.cfg"
    dest: /etc/mock/default.cfg
    state: link
    force: yes

- name: "enable copr repo for mock"
  blockinfile:
    block: |
      [freeipa_copr]
      name=Copr repo {{ freeipa_copr }}
      baseurl=https://copr-be.cloud.fedoraproject.org/results/{{ freeipa_copr }}/fedora-$releasever-$basearch/
      type=rpm-md
      skip_if_unavailable=True
      gpgcheck=1
      gpgkey=https://copr-be.cloud.fedoraproject.org/results/{{ freeipa_copr }}/pubkey.gpg
      repo_gpgcheck=0
      enabled=1
      enabled_metadata=1
    dest: /etc/mock/default.cfg
    insertbefore: '^\[fedora\]'

# TODO: optimize mock
# https://fedoraproject.org/wiki/Using_Mock_to_test_package_builds#Speeding_up

