---
basedir: /root/openclose_pr

nightly_jobs:
  - name: testing_master
    weekdays: "1,3,5"
    hour: "23"
    minute: "00"
  - name: testing_f28
    weekdays: "2,4"
    hour: "23"
    minute: "00"
  - name: testing_rawhide
    weekdays: "6"
    hour: "10"
    minute: "00"
  - name: testing_ipa-4.7
    weekdays: "7"
    hour: "10"
    minute: "00"
