- name: Turn off build-in OpenSSH server
  win_service:
    name: "sshd"
    state: "absent"

- name: Check if cygwin sshd service exists
  win_service:
    name: "{{ sshd_service }}"
  register: sshd_status

- when: not sshd_status.exists
  block:
  - name: donwload cygwin installer
    win_get_url:
      url: "{{ cygwin_installer_url }}"
      dest: "{{ cygwin_installer_local_file }}"

  - name: Install OpenSSH
    win_shell: >
      {{ cygwin_installer_local_file }}
      --quiet-mode
      --no-desktop
      --site {{ item }}
      --root {{ cygwin_dir }}
      --packages openssh
    failed_when: "'Installation incomplete' in (cygwin_result.stdout + cygwin_result.stderr)"
    register: cygwin_result
    ignore_errors: yes
    with_items: "{{ cygwin_mirror_urls }}"
    when: cygwin_result is undefined or cygwin_result.failed

  - name: Check Cygwin installation status
    vars:
      last_mirror_result: "{{ cygwin_result.results | rejectattr('skipped', 'defined') | list | last }}"
    assert:
      that: "not last_mirror_result.failed"
      fail_msg: |
        Cygwin installation failed with message:
        {{ last_mirror_result.stdout }}
        {{ last_mirror_result.stderr }}

- name: Create passwd file
  win_shell: "bin/mkpasswd > etc/passwd"
  args:
    chdir: "{{ cygwin_dir }}"
    creates: "{{ cygwin_dir }}/etc/passwd"
  register: passwd

- name: Configure ssh
  win_shell: '{{ cygwin_dir }}/bin/bash -c "export PATH=${PATH}:/bin; ssh-host-config -y -w Secret123"'
  args:
    creates: "{{ cygwin_dir }}/etc/ssh_config"
  register: ssh_config

- name: start sshd
  win_service:
    name: "{{ sshd_service }}"
    state: "{{ 'restarted' if passwd is changed or ssh_config is changed else 'started' }}"
