---
# tasks file for win-ad-forest
- name: Add adgroup1
  win_domain_group:
    name: adgroup1
    scope: global

- name: Add adgroup2
  win_domain_group:
    name: adgroup2
    scope: global

- name: Add aduser1
  win_shell: |
    $password = ConvertTo-SecureString -String "{{ ad_opts.SafeModeAdministratorPassword }}" -AsPlainText -Force

    New-ADUser \
      -AccountPassword $password \
      -PasswordNeverExpires $true \
      -Enabled $true \
      -GivenName Ad \
      -Surname User1 \
      -Name aduser1

    Add-ADGroupMember adgroup1 -Members aduser1
    Add-ADGroupMember adgroup2 -Members aduser1
  register: useradd_aduser1

- name: Add aduser2
  win_shell: |
    $password = ConvertTo-SecureString -String "{{ ad_opts.SafeModeAdministratorPassword }}" -AsPlainText -Force

    New-ADUser \
      -AccountPassword $password \
      -PasswordNeverExpires $true \
      -Enabled $true \
      -GivenName Ad \
      -Surname User2 \
      -Name aduser2
  register: useradd_aduser2

- name: Push Add-CrossForest-Group script
  win_template:
    src: Add-CrossForest-Group.ps1.j2
    dest: 'C:\Windows\Temp\Add-CrossForest-Group.ps1'

- name: Add-CrossForest-Group adunigroup1 aduser1
  win_shell: 'C:\Windows\Temp\Add-CrossForest-Group.ps1 adunigroup1 aduser1'
