version: 1
formatters:
    basic:
        format: '%(levelname)s:%(name)s:%(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: basic
root:
    level: WARNING
    handlers: [console]
loggers:
    __main__:
        level: DEBUG
    prci_github:
        level: DEBUG
    prci_github.adapter:
        level: WARNING
