---
- name: check if template directory has Vagrantfile
  stat:
    path: "{{ template_box_dir }}/Vagrantfile"
  register: vagrantfile

- name: destroy vagrant image
  become: true
  shell: vagrant destroy -f
  args:
    chdir: "{{ template_box_dir }}"
  when: vagrantfile.stat.exists is defined and vagrantfile.stat.exists
 
- name: remove the template directory
  become: true
  file:
    path: "{{ template_box_dir }}"
    state: absent
