---
- name: remove {{ fedora_nightly_template_dir }}
  file:
    path: "{{ fedora_nightly_template_dir }}"
    state: absent

- name: create {{ fedora_nightly_template_dir }} directory
  file:
    path: "{{ fedora_nightly_template_dir }}"
    state: directory

- name: download latest nightly box ({{ fedora_releasever }})
  shell: >
    wget -r -np -nH --cut-dirs=9 -A
    'Fedora-Cloud-Base-Vagrant-{{ fedora_version.capitalize() }}-*x86_64.vagrant-libvirt.box'
    {{ fedora_nightly_images_remote_dir }}
  args:
    chdir: "{{ fedora_nightly_template_dir }}"

- name: move the nightly box ({{ fedora_releasever }}) to latest
  shell: mv *.box latest.box
  args:
    chdir: "{{ fedora_nightly_template_dir }}"
