---
- hosts: cleanup_runners
  become: true
  become_method: sudo
  name: cleanup runners disk
  gather_facts: false

  vars:
    box_initial_name: "freeipa-VAGRANTSLASH"
    default_provider: "libvirt"

  vars_prompt:
    - name: box_name
      prompt: "Name of the box to be removed (eg: ci-master-f27)"
      private: false

    - name: box_version
      prompt: "Version of the box to be removed (eg: 0.1.0)"
      private: false

    - name: user_confirmation
      prompt: "Are you sure you want to remove this box? Answer with YES or NO"
      default: "NO"
      private: false

  tasks:
    - name: remove vagrant and libvirt box
      block:
        - name: remove box from vagrant
          shell: >
            vagrant box remove freeipa/{{ box_name }}
            --provider {{ default_provider }}
            --box-version {{ box_version }}
          register: res
          changed_when: res.rc == 0
          failed_when:
            res.rc != 0
            and "could not be found" not in res.stderr
            and "not installed" not in  res.stderr

        - name: delete image from libvirt
          shell: >
            virsh vol-delete --pool default
            {{ box_initial_name }}-{{ box_name }}_vagrant_box_image_{{ box_version }}.img
          register: res
          changed_when: res.rc == 0
          failed_when:
            res.rc != 0
            and "not found" not in res.stderr
      when: user_confirmation == "YES" and box_name != "" and box_version != ""
