repository:
    owner: {{ monitored_repo_owner }}
    name: {{ monitored_repo_name }}
credentials:
    token: {{ github_token }}
tasks_file: .freeipa-pr-ci.yaml
whitelist_file: /root/freeipa-pr-ci/whitelist.yml
no_task_backoff_time: {{ no_task_backoff_time }}
logging:
    version: 1
    formatters:
        basic:
            format: '%(levelname)s: %(name)s: %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: basic
    root:
        level: WARNING
        handlers: [console]
    loggers:
        __main__:
            level: DEBUG
        internals:
            level: DEBUG
