---
- name: "update distro packages"
  dnf:
    name: "*"
    state: latest

- name: "install freeipa rpms with dependencies"
  shell: "dnf install -y /root/rpmbuild/RPMS/*.rpm"

- name: "remove freeipa packages while keeping dependencies"
  shell: "rpm -e --nodeps '{{ item }}'"
  with_items:
    - freeipa-client
    - freeipa-client-common
    - freeipa-common
    - freeipa-debuginfo
    - freeipa-python-compat
    - freeipa-server
    - freeipa-server-common
    - freeipa-server-dns
    - freeipa-server-trust-ad
    - python2-ipaclient
    - python2-ipalib
    - python2-ipaserver
    - python2-ipatests
    - python3-ipaclient
    - python3-ipalib
    - python3-ipaserver
    - python3-ipatests

- name: "install ipa-vagrant-ci dependencies"
  dnf:
    name: PyYAML
    state: latest

- name: "install vim"
  dnf:
    name: vim
    state: latest
