---
- name: install packages for builder role
  dnf:
    state: latest
    name:
      - mock
      - git

- name: set default mock config
  template:
    src: templates/mock-fedora-{{ 'rawhide' if fedora_version == 'rawhide' else 'branched' }}.cfg.j2
    dest: /etc/mock/default.cfg
    force: yes
