---
# tasks file for win-ad-forest
- name: Add adgroup1
  win_domain_group:
    name: adgroup1
    scope: global
    state: present

- name: Add adgroup2
  win_domain_group:
    name: adgroup2
    scope: global
    state: present

- name: Add adunigroup1
  win_domain_group:
    name: adunigroup1
    scope: universal
    state: present

- name: Add aduser1
  win_shell: |
    $password = ConvertTo-SecureString -String "{{ ad_opts.SafeModeAdministratorPassword }}" -AsPlainText -Force

    New-ADUser \
      -AccountPassword $password \
      -PasswordNeverExpires $true \
      -Enabled $true \
      -GivenName Ad \
      -Surname User1 \
      -Name aduser1

    Add-ADGroupMember adgroup1 -Members aduser1
    Add-ADGroupMember adgroup2 -Members aduser1
    Add-ADGroupMember adunigroup1 -Members aduser1
  register: useradd_aduser1

- name: Add aduser2
  win_shell: |
    $password = ConvertTo-SecureString -String "{{ ad_opts.SafeModeAdministratorPassword }}" -AsPlainText -Force

    New-ADUser \
      -AccountPassword $password \
      -PasswordNeverExpires $true \
      -Enabled $true \
      -GivenName Ad \
      -Surname User2 \
      -Name aduser2

    Add-ADGroupMember adgroup1 -Members aduser2
  register: useradd_aduser2
